name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9]
        poetry-version: [1.1.12]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry ${{ matrix.poetry-version }}
      run: |
        python -m ensurepip
        pip install --upgrade pip
        pip install poetry==${{ matrix.poetry-version }}

    - name: Install dependencies
      run: poetry install

    - name: Test with pytest
      env:
        PYTHONPATH: "."
      run: |
        poetry run python -m pytest --cov=plz --cov-fail-under 60

    - name: Convert coverage to lcov
      # We only need to generate coverage once
      if: matrix.python-version == '3.9'
      run: |
        pip install coveragepy-lcov
        coveragepy-lcov

    - name: Coveralls
      # We only need to generate coverage once
      if: matrix.python-version == '3.9'
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "./lcov.info"
