name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10", 3.11]
        poetry-version: [1.1.13]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry ${{ matrix.poetry-version }}
      run: |
        pip install poetry==${{ matrix.poetry-version }}

    - name: Install dependencies
      run: poetry install

    - name: Test with pytest
      run: poetry run coverage run -m pytest

    - name: Generate lcov
      # We only need to generate coverage once
      if: matrix.python-version == 3.11
      run: poetry run coverage lcov

    - name: Coveralls
      # We only need to generate coverage once
      if: matrix.python-version == 3.11
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "./coverage.lcov"
